### PR TITLE
Fixes ENOENT issue when a folder is added and quickly removed

### PR DESCRIPTION
**Pull request by alexgorbatchev**
This issue was occurring for me while watching files. A unit test would create a folder and remove it before `readdirSync` had a chance to read it, thereby causing an exception.

### CODE REVIEW

**Comment by shama** [comment]
Thanks!

**Comment by alexgorbatchev** [comment]
@shama could you please publish this?

I know you are probably very busy, if you would like some help with this, I'm a maintainer and publisher for lots of NPM modules and would gladly take care of basic house keeping for this module here and there :)

My NPM is https://www.npmjs.com/~alexgorbatchev
My Github is https://github.com/alexgorbatchev

Add me on NPM with the `npm owner add alexgorbatchev` and on Github as a contributor.

Cheers!

**Comment by shama** [comment]
@alexgorbatchev Thanks for the ping! I'm rebuilding the Windows tests and then will publish a new patch. I've added you as an owner of this project as well. Thanks for your help!

**Comment by shama** [comment]
Published as `1.1.2`. Thanks!

**Comment by alexgorbatchev** [comment]
Thank you so much! 👍  💯

**Pull request merged**
